"""Workflow YAML template for the /workflow create command."""

WORKFLOW_CREATE_PROMPT = (
    "Create a MoCode workflow YAML file based on this description: {description}\n\n"
    "The workflow YAML format:\n"
    "```yaml\n"
    "name: my-workflow\n"
    "description: description text\n"
    "max_iterations: 100          # optional, default 100\n"
    "\n"
    "nodes:\n"
    "  # ── Root task node ─────────────────────────────────\n"
    "  - id: overview\n"
    "    description: Analyze project structure\n"
    "    task: Analyze project structure in {{args.path}}\n"
    "\n"
    "  # ── Parallel task nodes ────────────────────────────\n"
    "  # depends is AUTO-INFERRED from {{nodes.X.output}} references\n"
    "  - id: check_security\n"
    "    description: Review security issues\n"
    "    task: Review security issues in {{nodes.overview.output}}\n"
    "    # no depends needed — inferred from {{nodes.overview.output}}\n"
    "\n"
    "  - id: check_style\n"
    "    description: Review style issues\n"
    "    task: Review style issues in {{nodes.overview.output}}\n"
    "    # no depends needed — inferred from {{nodes.overview.output}}\n"
    "\n"
    "  # ── Converge node ──────────────────────────────────\n"
    "  # references multiple upstream nodes → depends inferred for all\n"
    "  - id: summary\n"
    "    description: Generate final summary\n"
    "    task: |\n"
    "      Security: {{nodes.check_security.output}}\n"
    "      Style: {{nodes.check_style.output}}\n"
    "\n"
    "  # ── Router node ────────────────────────────────────\n"
    "  # Routers ALWAYS need explicit depends (no task template to infer from)\n"
    "  - id: decide\n"
    "    type: router\n"
    "    depends: [summary]\n"
    "    routes:\n"
    "      - match: \"critical\"     # regex match on dependency outputs\n"
    "        to: [fix]             # activate fix node\n"
    "      - match: null            # fallback (no match pattern)\n"
    "        to: [done]\n"
    "\n"
    "  # ── Router-gated node ──────────────────────────────\n"
    "  # depends on router (explicit) + upstream data (auto-inferred)\n"
    "  - id: fix\n"
    "    description: Fix critical issues\n"
    "    task: Fix critical issues from {{nodes.summary.output}}\n"
    "\n"
    "  # ── Router with loop (back-edge) ───────────────────\n"
    "  - id: verify_router\n"
    "    type: router\n"
    "    depends: [fix]\n"
    "    routes:\n"
    "      - match: \"FAIL\"\n"
    "        to: [fix]             # back-edge → loop\n"
    "        max: 3                # max 3 retries\n"
    "      - match: null\n"
    "        to: [done]\n"
    "\n"
    "  # ── Convergence point ──────────────────────────────\n"
    "  # Gate-only dependency on routers (no data reference)\n"
    "  - id: done\n"
    "    description: Generate final report\n"
    "    task: |\n"
    "      Generate final report.\n"
    "      Overview: {{nodes.overview.output}}\n"
    "    depends: [decide, verify_router]  # explicit: wait for these routers\n"
    "```\n\n"
    "IMPORTANT RULES:\n"
    "1. **Task nodes**: `depends` is auto-inferred from `{{nodes.<id>.*}}` references\n"
    "   in the task template. Only add explicit `depends` for:\n"
    "   - Dependencies on router nodes (no output to reference)\n"
    "   - Ordering constraints without data dependency (e.g., cleanup after all)\n"
    "2. **Router nodes**: ALWAYS need explicit `depends` — there is no task\n"
    "   template to infer from. The `depends` defines which outputs to evaluate.\n"
    "3. Every node should have a brief `description` field shown in the UI.\n"
    "4. Router fallback: use `match: null` as the last route for unmatched input.\n"
    "5. Loop safety: back-edge routes must have `max: <N>` to prevent infinite loops.\n\n"
    "Template variables: {{args.key}}, {{nodes.id.output}}, {{nodes.id.exit_code}}, "
    "{{nodes.id.error}}, {{nodes.id.duration}}, {{previous}}, {{env.VAR}}\n\n"
    "Save the file to .mocode/workflows/<name>.yaml in the current project directory. "
    "Create the .mocode/workflows/ directory if it does not exist."
)
